<script lang="ts">
	import plot from '../assets/newplot.png'
</script>

<h1 class="font-mono text-4xl mt-10 text-emerald-500 text-center">How does the categorisation work?</h1>
<div class="max-w-5xl md:mx-auto text-xl mx-6">
	<p class="mt-6 border-l-3 pl-4 border-emerald-500"><span class="font-bold">TL;DR</span>: We use a machine learning model to represent video metadata as vectors in a high-dimensional vector space. We then project that space to low dimension for visualisation and clustering, using another model. We finally use a clustering algorithm to classify semantically similar neighbors into a single category. The last step was done manually here.</p>
	<p class="mt-6">At its core, <span class="text-emerald-500 font-display text-2xl">magpie</span> uses a machine learning model trained on my own "watch later" playlist's videos. The first step is to take each video from the playlist and "clean" it so that future steps have a higher signal to noise ratio. We then need to make sure that the data being fed to the transformer is as <span class="italic">relevant</span> to the video content as possible, as that would decide what the output of the transformer looks like. </p>
	<p class="mt-6">The next step is to map this clean data to a vector space, in order to generate something called an <span class="font-bold">embedding</span>. Words can be thought of as a vector of floats. Two vectors that are close to each other in that vector space have some semantic similarity. Here we use a metric called <span class="font-bold">cosine similarity</span>, which measures the angle between two vectors. Thus two words are similar if they are used in similar contexts. This idea generalises well to sentences and paragraphs too, which is exactly what we are dealing with here. </p>
	<p class="mt-6">I have used the Sentence-Transformers library here, in particular, the <span class="text-amber-200">all-MiniLM-L6-v2</span> model. This model specifically generates a 384-dimension vector which is learnable by a neural net - that is what produces the contextualized embeddings. Here the relevance of the data is of most importance, as by default, input text longer than 256 word pieces is truncated. The sentence vector produced can now be used for an operation called <span class="font-bold">clustering</span>, which is essentially grouping of similar things.</p>
	<p class="mt-6">Before we do that though, we need to perform <span class="font-bold">dimensionality reduction</span> on these embeddings. This is done so that we get a low-dimensional representation that retains some meaningful properties of the original data. Why can't we work in the high-dimension space itself? Essentially, when dimensionality increases, the volume of the vector space increases so fast that the available data becomes sparse and semantically valuable context is lost. Also, organising data in this space is undesirable as all objects appear to be sparse and dissimilar in many ways, which prevents common data organisation strategies. Thus, there is a need for dimensionality reduction. I have used the UMAP model here which projects the high-dimensional vectors into a low, two-dimensional space. </p>
	<p class="mt-6">We now turn our attention to the problem at hand itself - clustering. I chose the HDBSCAN algorithm for this job. I did that because it was hierarchal and density-based. Using something like k-means would've meant guessing the number of categories myself, which is something I did not want to do. HDBSCAN also pairs nicely with UMAP, and Sentence-Transformers to UMAP to HDBSCAN is quite the popular pipeline for content categorisation tasks. I also used the <span class="text-amber-200">cosine</span> metric for HDBSCAN, so that it uses cosine similarity to find out the semantic similarity between two sentence vectors. In my case, I visualised the clusters from HDBSCAN as below: </p>
	<img src={plot} alt="plot" class="mt-6"/>
	<p class="mt-1 text-lg text-amber-200">The grey dots represent the videos that could not be categorised into any cluster - this later forms the <span class="italic">Mixed Bag</span> genre in our selection.</p>
	<p class="mt-6">Now comes human intervention. Or, if you're feeling brave today, you could use LLMs for this. But I wanted to do this myself. The next step indeed is to look at all the clusters and find some connected links between them, in order to give it a name. For example, you spot a neighborhood of dots, all of which seem like they belong to the 'Horror' cluster. Then you simply assign that label to that cluster, and call it a day. That is the simplest form of content categorisation and is what I did here. One could also go one step beyond and train a classifier based on those labels provided earlier, but that is something that I didn't do here, mostly because I didn't want to.</p>
	<p class="mt-6">For more information, feel free to give the README a read.
</p>
</div>

