<script>
</script>

<h1 class="font-mono text-4xl mt-10 text-emerald-500 text-center">The core idea behind this project</h1>
<div class="max-w-5xl mx-auto text-xl">
<p class="mt-6">I have been using YouTube for about nine years at this point. Over time, my viewing preferences have changed a lot. It can be hard to keep track of those changing preferences, and I would have liked a native way inside YouTube to cateagorise videos so that I know what I am/was really into at any point.</p>
<p class="mt-6">One might say that such a categorisation already exists, and they are right - it is the <code class="text-amber-200">Category</code> attribute assigned to every video via YouTube's own machine-learning algorithm. But it's bad - <span class="italic">really</span> bad, as it very frequently mis-categorises videos. YouTube as a platform doesn't really care about it, as their entire brand is based on a randomised selection of videos curated for you via a blackbox algorithm.</p>
<p class="mt-6">I think that's fine, but I would really want to know what the current "map" of my interests looks like, especially on a website like YouTube, which I use a lot. They do provide you with a "map" at the end of the year - which is the personalised YouTube rewind for every user. It's more accurate and reflects one's interests faithfully. "What if there was something like that, but available at all times?" - that was my initial thought before starting this project.</p>
<p class="mt-6">Platforms like Netflix and Hulu have their entire selection based off a genre-based classfication. They do not serve "random" content to the user - their videos are categorised cleanly into buckets. This has some very real advantages. Firstly, the user can easily search through a genre and find something they'd like to watch. If they like something from genre A, they could watch something else from it rather than hoping that a blackbox algorithm drops a video from genre A again in their "feed".</p>
<p class="mt-6">Secondly, it makes it easier for the user themselves to know what they are into. This information helps them understand their own interests more, as well as convey it to others. The question, "What do you watch on YouTube these days?" could have a much more succint answer if I said "Horror Gaming" or "Video Essays", instead of mentioning the names of six channels from that bucket. The former is a more high-signal statement than the latter.</p>
<h2 class="text-3xl text-emerald-500 mt-6">A more personal reason</h2>
<p class="mt-6">Collecting data on myself is always an interesting activity. As I have mentioned before, getting a map of what I am into at any point is always a great thing, because it exposes underlying patterns in my own cognition or interests that I was unaware of. This project serves as a way for me to achieve that as its core manifests in one of the most common problems in machine learning - content categorisation. The last point is important because I am still a beginner in machine learning, so I am always looking for beginner-friendly and personal problems to work on. This ticked all the boxes for me. I had fun making it :)</p>
</div>
